name: snueco
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  
  
  

  cached_network_image: ^3.4.1

  # firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  firebase_database: ^10.5.5
  firebase_storage: ^11.0.0
  #firebase_performance:

  collection: ^1.18.0
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  expandable: ^5.0.1
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  font_awesome_flutter: ^10.8.0
  from_css_color: ^2.0.0

  go_router: 7.1.1
  google_fonts: ^6.2.1
  # google_mobile_ads: ^5.1.0

  html: ^0.15.5+1
  http: ^1.0.0
  intl: ^0.19.0
  json_path: ^0.7.5
  page_transition: ^2.2.1
  path_provider: ^2.1.3

  plugin_platform_interface: ^2.1.8
  provider: ^6.1.4
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.2.1

  sqflite: ^2.4.2
  stream_transform: ^2.1.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1

  #flutter_blue:
  flutter_blue_plus: ^1.35.3
  # flutter_beacon: ^0.5.1
  flutter_beacon:
    path: packages/flutter_beacon

  get: ^4.7.2
  permission_handler: ^11.4.0
  flutter_background_service: ^5.1.0

  flutter_local_notifications: ^19.0.0
  device_info_plus: ^11.3.3

  # model
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_barcode_scanner: ^2.0.0

  # animation
  rive: ^0.13.20



dependency_overrides:
  flutter_barcode_scanner:
    git:
      url: https://github.com/decodevM/flutter_barcode_scanner
      ref: flutter-3.29 # This parameter is responsible for which branch to use
  web: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  # image: ^4.2.0
  lints: ^5.1.1

  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15

  # model
  freezed: ^3.0.6
  json_serializable: ^6.9.4

  flutter_gen_runner: ^5.10.0

flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: false
  web:
    generate: false
  image_path: "assets/images/ios_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: "NotoSans"
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
